version: "3.8"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: [ "sh", "-c", "cd /app && /app/.venv/bin/uvicorn --proxy-headers --forwarded-allow-ips=* --reload --host 0.0.0.0 server.main:app" ]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./data:/data
      - ./server/server:/app/server
      - ./server/alembic:/app/alembic
    env_file: ./server/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  default:
    external: true
    name: npm
