"""Flags and player restrictions

Revision ID: 0925bf19d341
Revises: 9ef792bc3a9c
Create Date: 2025-02-07 21:58:03.176197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0925bf19d341"
down_revision: Union[str, None] = "9ef792bc3a9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mwsessions", sa.Column("allowed_users", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("mwsessions", sa.Column("flags", sa.JSON(), nullable=True))

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE eventtypes ADD VALUE IF NOT EXISTS 'player_kicked'")
        op.execute("ALTER TYPE eventtypes ADD VALUE IF NOT EXISTS 'user_join_chat'")
        op.execute("UPDATE mwsessions SET flags = '{}'::json")
        op.execute("UPDATE mwsessions SET allowed_users = '{}'::text[]")

    op.alter_column("mwsessions", "flags", existing_type=sa.JSON(), nullable=False)
    op.alter_column(
        "mwsessions",
        "allowed_users",
        existing_type=sa.ARRAY(sa.String()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mwsessions", "flags")
    op.drop_column("mwsessions", "allowed_users")
    # ### end Alembic commands ###
