"""Remove unnecessary indexes

Revision ID: 0b55c84c67f1
Revises: 43ba758cce62
Create Date: 2024-12-30 20:58:52.702433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b55c84c67f1'
down_revision: Union[str, None] = '43ba758cce62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_description', table_name='games')
    op.drop_index('ix_logs_content', table_name='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_logs_content', 'logs', ['content'], unique=False)
    op.create_index('ix_games_description', 'games', ['description'], unique=False)
    # ### end Alembic commands ###
