"""Add frame time to item events

Revision ID: 43ba758cce62
Revises: 86fb260a1ee4
Create Date: 2024-09-15 12:29:23.396400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ba758cce62'
down_revision: Union[str, None] = '86fb260a1ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('frame_time', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_events_frame_time'), 'events', ['frame_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_frame_time'), table_name='events')
    op.drop_column('events', 'frame_time')
    # ### end Alembic commands ###
