"""Non player chat support

Revision ID: 9ac04c2a0a32
Revises: 9ef792bc3a9c
Create Date: 2025-02-01 17:50:55.892520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac04c2a0a32'
down_revision: Union[str, None] = '9ef792bc3a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    with op.get_context().autocommit_block():
        op.execute(
           "ALTER TYPE eventtypes ADD VALUE IF NOT EXISTS \'user_join_chat\'"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Removing the enum is dangerous so we will leave it in place.

    # ### end Alembic commands ###
