"""Fix user session links

Revision ID: fdb25dd1c281
Revises: 0925bf19d341
Create Date: 2025-02-09 14:36:56.828091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdb25dd1c281'
down_revision: Union[str, None] = '0925bf19d341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'last_used',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('events', 'from_player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'to_player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=postgresql.ENUM('session_create', 'player_join', 'failed_join', 'player_leave', 'chat', 'command', 'new_item', 'player_forfeit', 'player_pause_receive', 'player_resume_receive', 'user_join_chat', 'player_kicked', name='eventtypes'),
               nullable=False)
    op.alter_column('events', 'event_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('games', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('logs', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('logs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mwsessions', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mwsessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mwsessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mwsessions', 'tournament',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mwsessions', 'allowed_users',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('mwsessions', 'mwdata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sramstores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sramstores', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sramstores', 'player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sramstores', 'sram',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_sessions', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'bot',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'username_as_player_name',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'supporter',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'supporter',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'username_as_player_name',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'bot',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sramstores', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sramstores', 'sram',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sramstores', 'player',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sramstores', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sramstores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mwsessions', 'mwdata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('mwsessions', 'allowed_users',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('mwsessions', 'tournament',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mwsessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mwsessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mwsessions', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('games', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'event_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('events', 'event_type',
               existing_type=postgresql.ENUM('session_create', 'player_join', 'failed_join', 'player_leave', 'chat', 'command', 'new_item', 'player_forfeit', 'player_pause_receive', 'player_resume_receive', 'user_join_chat', 'player_kicked', name='eventtypes'),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'to_player',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'from_player',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'last_used',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
